[project]
name = "aicamerajack"
version = "0.1.0"
description = ""
authors = [
    {name = "Konstantin Losev",email = "losev.konstantin6@wb.ru"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "label-studio (>=1.20.0,<2.0.0)",
    "ultralytics (>=8.3.203,<9.0.0)",
    "model-compression-toolkit (>=2.4.2,<3.0.0)",
    "imx500-converter[pt] (>=3.17.3,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
